# Generated by Django 5.0 on 2024-04-10 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_airplane_created_by_user_airport_created_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='capacity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
