# Generated by Django 5.0 on 2024-04-06 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticket', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='recordOfTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_card_number', models.CharField(max_length=16)),
                ('credit_card_name', models.CharField(max_length=80)),
                ('credit_card_ccv', models.CharField(max_length=3)),
                ('credit_card_year', models.CharField(max_length=4)),
                ('credit_card_month', models.CharField(max_length=2)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ticket.ticket', verbose_name='Field of ticket')),
            ],
        ),
    ]
