# Generated by Django 5.0 on 2024-04-06 21:54

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flight', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatNumber', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('isReserved', models.BooleanField(blank=True, default=False)),
                ('flightID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Flight_rel', to='flight.flight', verbose_name='id to flight')),
                ('userReserved', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_rel', to=settings.AUTH_USER_MODEL, verbose_name='id to user')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999)])),
                ('unique_id', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('active', models.BooleanField(default=True, verbose_name='being status : ')),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight', to='flight.flight')),
                ('seatID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ticket.seats', verbose_name='seat ticket id')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('tickets', django.db.models.manager.Manager()),
            ],
        ),
    ]
